dehazeformer:
  name: "dehazeformer-b"
  checkpoint_path: "weights/dehazeformer-b.pth"
  download_url: ""
  params: {}

retinexformer:
  name: "retinexformer-lol-v2-real"
  checkpoint_path: "weights/LOL_v2_real.pth"
  download_url: ""
  params:
    in_channels: 3
    out_channels: 3
    n_feat: 40
    stage: 1
    num_blocks: [1, 2, 2]

restormer:
  name: "restormer-derain"
  checkpoint_path: "weights/deraining.pth"
  download_url: "https://github.com/swz30/Restormer/releases/download/v1.0/deraining.pth"
  params: {}

restormer_denoise:
  name: "restormer-real-denoise"
  checkpoint_path: "weights/real_denoising.pth"
  download_url: "https://github.com/swz30/Restormer/releases/download/v1.0/real_denoising.pth"
  params: {}
